// <auto-generated />
using System;
using Budget.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Budget.DATA.Migrations
{
    [DbContext(typeof(BudgetContext))]
    [Migration("20200528122402_alterbanksubFamily")]
    partial class alterbanksubFamily
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Budget.MODEL.AsEvolutionCdbDto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Balance");

                    b.Property<double>("Credit");

                    b.Property<double>("Debit");

                    b.Property<string>("Month");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.ToTable("AsEvolutionDto");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AlertThreshold")
                        .HasColumnName("ALERT_THRESHOLD");

                    b.Property<int>("IdAccountType")
                        .HasColumnName("ID_ACCOUNT_TYPE");

                    b.Property<int>("IdBankAgency")
                        .HasColumnName("ID_BANK_AGENCY");

                    b.Property<int>("IdUserOwner")
                        .HasColumnName("ID_USER_OWNER");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.Property<string>("Number")
                        .HasColumnName("NUMBER")
                        .HasMaxLength(50);

                    b.Property<double>("StartAmount")
                        .HasColumnName("START_AMOUNT");

                    b.HasKey("Id");

                    b.HasIndex("IdAccountType");

                    b.HasIndex("IdBankAgency");

                    b.HasIndex("IdUserOwner");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasName("IX_AccountNumber")
                        .HasFilter("[NUMBER] IS NOT NULL");

                    b.ToTable("ACCOUNT","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountOperation")
                        .HasColumnName("AMOUNT_OPERATION");

                    b.Property<DateTime>("DateImport")
                        .HasColumnName("DATE_IMPORT");

                    b.Property<DateTime?>("DateIntegration")
                        .HasColumnName("DATE_INTEGRATION");

                    b.Property<DateTime?>("DateOperation")
                        .HasColumnName("DATE_OPERATION");

                    b.Property<int>("IdAccount")
                        .HasColumnName("ID_ACCOUNT");

                    b.Property<int>("IdImport")
                        .HasColumnName("ID_IMPORT");

                    b.Property<int>("IdMovement")
                        .HasColumnName("ID_MOVEMENT");

                    b.Property<int>("IdOperation")
                        .HasColumnName("ID_OPERATION");

                    b.Property<int>("IdOperationDetail")
                        .HasColumnName("ID_OPERATION_DETAIL");

                    b.Property<int>("IdOperationMethod")
                        .HasColumnName("ID_OPERATION_METHOD");

                    b.Property<int>("IdOperationType")
                        .HasColumnName("ID_OPERATION_TYPE");

                    b.Property<int>("IdOperationTypeFamily")
                        .HasColumnName("ID_OPERATION_TYPE_FAMILY");

                    b.Property<string>("LabelOperation")
                        .HasColumnName("LABEL_OPERATION")
                        .HasMaxLength(500);

                    b.Property<string>("Reference")
                        .HasColumnName("REFERENCE")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdImport");

                    b.HasIndex("IdOperation");

                    b.HasIndex("IdOperationDetail");

                    b.HasIndex("IdOperationMethod");

                    b.HasIndex("IdOperationType");

                    b.HasIndex("IdOperationTypeFamily");

                    b.ToTable("ACCOUNT_STATEMENT","as");
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatementImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateImport")
                        .HasColumnName("DATE_IMPORT");

                    b.Property<string>("FileImport")
                        .HasColumnName("FILE_IMPORT");

                    b.Property<int>("IdBankAgency")
                        .HasColumnName("ID_BANK_AGENCY");

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id");

                    b.HasIndex("IdBankAgency");

                    b.HasIndex("IdUser");

                    b.ToTable("ACCOUNT_STATEMENT_IMPORT","as");
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatementImportFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AmountOperation")
                        .HasColumnName("AMOUNT_OPERATION");

                    b.Property<DateTime>("DateImport")
                        .HasColumnName("DATE_IMPORT");

                    b.Property<DateTime?>("DateIntegration")
                        .HasColumnName("DATE_INTEGRATION");

                    b.Property<DateTime?>("DateOperation")
                        .HasColumnName("DATE_OPERATION");

                    b.Property<int?>("IdAccount")
                        .HasColumnName("ID_ACCOUNT");

                    b.Property<int>("IdImport")
                        .HasColumnName("ID_IMPORT");

                    b.Property<int>("IdMovement")
                        .HasColumnName("ID_MOVEMENT");

                    b.Property<int>("IdOperation")
                        .HasColumnName("ID_OPERATION");

                    b.Property<int>("IdOperationDetail")
                        .HasColumnName("ID_OPERATION_DETAIL");

                    b.Property<int>("IdOperationMethod")
                        .HasColumnName("ID_OPERATION_METHOD");

                    b.Property<int>("IdOperationType")
                        .HasColumnName("ID_OPERATION_TYPE");

                    b.Property<int>("IdOperationTypeFamily")
                        .HasColumnName("ID_OPERATION_TYPE_FAMILY");

                    b.Property<int>("IdState")
                        .HasColumnName("ID_STATE");

                    b.Property<bool>("IsDuplicated")
                        .HasColumnName("IS_DUPLICATED");

                    b.Property<string>("LabelOperation")
                        .HasColumnName("LABEL_OPERATION")
                        .HasMaxLength(500);

                    b.Property<string>("LabelOperationWork")
                        .HasColumnName("LABEL_OPERATION_WORK")
                        .HasMaxLength(500);

                    b.Property<string>("OperationKeywordTemp")
                        .HasColumnName("OPERATION_KEYWORD_TEMP");

                    b.Property<string>("OperationLabelTemp")
                        .HasColumnName("OPERATION_LABEL_TEMP");

                    b.Property<string>("OperationReferenceTemp")
                        .HasColumnName("OPERATION_REFERENCE_TEMP");

                    b.Property<string>("PlaceKeywordTemp")
                        .HasColumnName("PLACE_KEYWORD_TEMP")
                        .HasMaxLength(500);

                    b.Property<string>("PlaceLabelTemp")
                        .HasColumnName("PLACE_LABEL_TEMP")
                        .HasMaxLength(500);

                    b.Property<string>("Reference")
                        .HasColumnName("REFERENCE")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdImport");

                    b.HasIndex("IdOperation");

                    b.HasIndex("IdOperationDetail");

                    b.HasIndex("IdOperationMethod");

                    b.HasIndex("IdOperationType");

                    b.HasIndex("IdOperationTypeFamily");

                    b.HasIndex("IdState");

                    b.ToTable("ACCOUNT_STATEMENT_IMPORT_FILE","as");
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatementPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAccountStatement")
                        .HasColumnName("ID_ACCOUNT_STATEMENT");

                    b.Property<int>("IdPlan")
                        .HasColumnName("ID_PLAN");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdAccountStatement", "IdPlan")
                        .IsUnique()
                        .HasName("IX_ASP_IdAccountStatement_IdPlan");

                    b.ToTable("ACCOUNT_STATEMENT_PLAN","as");
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("ACCOUNT_TYPE","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Extension")
                        .HasColumnName("EXTENSION")
                        .HasMaxLength(100);

                    b.Property<int>("IdFamily")
                        .HasColumnName("ID_FAMILY");

                    b.Property<string>("Name")
                        .HasColumnName("NAME")
                        .HasMaxLength(100);

                    b.Property<string>("Path")
                        .HasColumnName("PATH")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("ASSET","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankAgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdBankSubFamily")
                        .HasColumnName("ID_BANK_SUB_FAMILY");

                    b.Property<int>("IdGMapAddress")
                        .HasColumnName("ID_GMAP_ADDRESS");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("IdBankSubFamily");

                    b.HasIndex("IdGMapAddress");

                    b.ToTable("BANK_AGENCY","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasMaxLength(4);

                    b.Property<int>("IdAsset")
                        .HasColumnName("ID_ASSET");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdAsset");

                    b.ToTable("BANK_FAMILY","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankFileDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdBankFamily")
                        .HasColumnName("ID_BANK_FAMILY");

                    b.Property<string>("LabelField")
                        .HasColumnName("LABEL_FIELD")
                        .HasMaxLength(50);

                    b.Property<int>("LabelOrder")
                        .HasColumnName("LABEL_ORDER");

                    b.HasKey("Id");

                    b.HasIndex("IdBankFamily");

                    b.ToTable("BANK_FILE_DEFINITION","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankSubFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasMaxLength(10);

                    b.Property<int>("IdAsset")
                        .HasColumnName("ID_ASSET");

                    b.Property<int>("IdBankFamily")
                        .HasColumnName("ID_BANK_FAMILY");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("IdBankFamily");

                    b.ToTable("BANK_SUB_FAMILY","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FormattedAddress")
                        .IsRequired()
                        .HasColumnName("FORMATTED_ADDRESS");

                    b.Property<double>("Lat")
                        .HasColumnName("LAT");

                    b.Property<double>("Lng")
                        .HasColumnName("LNG");

                    b.Property<int>("idGMapAdministrativeAreaLevel1")
                        .HasColumnName("ID_GMAP_ADMINISTRATIVE_AREA_LEVEL_1");

                    b.Property<int>("idGMapAdministrativeAreaLevel2")
                        .HasColumnName("ID_GMAP_ADMINISTRATIVE_AREA_LEVEL_2");

                    b.Property<int>("idGMapCountry")
                        .HasColumnName("ID_GMAP_COUNTRY");

                    b.Property<int>("idGMapLocality")
                        .HasColumnName("ID_GMAP_LOCALITY");

                    b.Property<int>("idGMapNeighborhood")
                        .HasColumnName("ID_GMAP_NEIGHBORHOOD");

                    b.Property<int>("idGMapPostalCode")
                        .HasColumnName("ID_GMAP_POSTAL_CODE");

                    b.Property<int>("idGMapRoute")
                        .HasColumnName("ID_GMAP_ROUTE");

                    b.Property<int>("idGMapStreetNumber")
                        .HasColumnName("ID_GMAP_STREET_NUMBER");

                    b.Property<int>("idGMapSublocalityLevel1")
                        .HasColumnName("ID_GMAP_SUBLOCALITY_LEVEL_1");

                    b.Property<int>("idGMapSublocalityLevel2")
                        .HasColumnName("ID_GMAP_SUBLOCALITY_LEVEL_2");

                    b.HasKey("Id");

                    b.HasIndex("idGMapAdministrativeAreaLevel1");

                    b.HasIndex("idGMapAdministrativeAreaLevel2");

                    b.HasIndex("idGMapCountry");

                    b.HasIndex("idGMapLocality");

                    b.HasIndex("idGMapNeighborhood");

                    b.HasIndex("idGMapPostalCode");

                    b.HasIndex("idGMapRoute");

                    b.HasIndex("idGMapStreetNumber");

                    b.HasIndex("idGMapSublocalityLevel1");

                    b.HasIndex("idGMapSublocalityLevel2");

                    b.ToTable("GMAP_ADDRESS","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapAddressType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGMapAddress")
                        .HasColumnName("ID_GMAP_ADDRESS");

                    b.Property<int>("IdGMapType")
                        .HasColumnName("ID_GMAP_TYPE");

                    b.HasKey("Id");

                    b.HasIndex("IdGMapAddress");

                    b.HasIndex("IdGMapType");

                    b.ToTable("GMAP_ADDRESS_TYPE","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapAdministrativeAreaLevel1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_ADMINISTRATIVE_AREA_LEVEL_1","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapAdministrativeAreaLevel2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_ADMINISTRATIVE_AREA_LEVEL_2","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapCountry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_COUNTRY","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapLocality", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_LOCALITY","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapNeighborhood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_NEIGHBORHOOD","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapPostalCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_POSTAL_CODE","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapRoute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_ROUTE","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapStreetNumber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_STREET_NUMBER","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapSublocalityLevel1", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_SUBLOCALITY_LEVEL_1","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapSublocalityLevel2", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("GMAP_SUBLOCALITY_LEVEL_2","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasColumnName("KEYWORD");

                    b.HasKey("Id");

                    b.ToTable("GMAP_TYPE","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapTypeLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnName("LANGUAGE_CODE");

                    b.Property<int>("IdGMapType")
                        .HasColumnName("ID_GMAP_TYPE");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.HasIndex("IdGMapType");

                    b.ToTable("GMAP_TYPE_LANGUAGE","gmap");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Month", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LabelLong")
                        .HasColumnName("LABEL_LONG");

                    b.Property<string>("LabelShort")
                        .HasColumnName("LABEL_SHORT");

                    b.Property<string>("LanguageCode")
                        .HasColumnName("LANGUAGE_CODE");

                    b.Property<string>("Number")
                        .HasColumnName("NUMBER");

                    b.HasKey("Id");

                    b.ToTable("MONTH","gen");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Operation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdOperationMethod")
                        .HasColumnName("ID_OPERATION_METHOD");

                    b.Property<int>("IdOperationType")
                        .HasColumnName("ID_OPERATION_TYPE");

                    b.Property<int>("IdUserGroup")
                        .HasColumnName("ID_USER_GROUP");

                    b.Property<bool>("IsMandatory")
                        .HasColumnName("IS_MANDATORY");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL")
                        .HasMaxLength(255);

                    b.Property<string>("Reference")
                        .HasColumnName("REFERENCE")
                        .HasMaxLength(20);

                    b.HasKey("Id");

                    b.HasIndex("IdOperationMethod");

                    b.HasIndex("IdOperationType");

                    b.HasIndex("Label", "IdOperationMethod", "IdOperationType")
                        .IsUnique()
                        .HasName("IX_OperationKey");

                    b.ToTable("OPERATION","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdGMapAddress")
                        .HasColumnName("ID_GMAP_ADDRESS");

                    b.Property<int>("IdOperation")
                        .HasColumnName("ID_OPERATION");

                    b.Property<int>("IdUserGroup")
                        .HasColumnName("ID_USER_GROUP");

                    b.Property<bool>("IsMandatory")
                        .HasColumnName("IS_MANDATORY");

                    b.Property<string>("KeywordOperation")
                        .HasColumnName("KEYWORD_OPERATION");

                    b.Property<string>("KeywordPlace")
                        .HasColumnName("KEYWORD_PLACE");

                    b.HasKey("Id");

                    b.HasIndex("IdGMapAddress");

                    b.HasIndex("IdOperation");

                    b.HasIndex("KeywordOperation", "KeywordPlace", "IdUserGroup")
                        .IsUnique()
                        .HasName("IX_Keyword")
                        .HasFilter("[KEYWORD_OPERATION] IS NOT NULL AND [KEYWORD_PLACE] IS NOT NULL");

                    b.ToTable("OPERATION_DETAIL","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("OPERATION_METHOD","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationMethodLexical", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdBankFamily")
                        .HasColumnName("ID_BANK_FAMILY");

                    b.Property<int>("IdOperationMethod")
                        .HasColumnName("ID_OPERATION_METHOD");

                    b.Property<string>("Keyword")
                        .HasColumnName("KEYWORD")
                        .HasMaxLength(50);

                    b.Property<int>("OrderId")
                        .HasColumnName("ORDER_ID");

                    b.HasKey("Id");

                    b.HasIndex("IdOperationMethod");

                    b.ToTable("OPERATION_METHOD_LEXICAL","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTransverse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnName("LABEL")
                        .HasMaxLength(255);

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("OPERATION_TRANSVERSE","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTransverseAs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAccountStatement")
                        .HasColumnName("ID_ACCOUNT_STATEMENT");

                    b.Property<int>("IdOperationTransverse")
                        .HasColumnName("ID_OPERATION_TRANSVERSE");

                    b.HasKey("Id");

                    b.HasIndex("IdAccountStatement");

                    b.HasIndex("IdOperationTransverse");

                    b.ToTable("OPERATION_TRANSVERSE_AS","as");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTransverseAsif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAccountStatementImportFile")
                        .HasColumnName("ID_ACCOUNT_STATEMENT_IMPORT_FILE");

                    b.Property<int>("IdOperationTransverse")
                        .HasColumnName("ID_OPERATION_TRANSVERSE");

                    b.HasKey("Id");

                    b.HasIndex("IdAccountStatementImportFile");

                    b.HasIndex("IdOperationTransverse");

                    b.ToTable("OPERATION_TRANSVERSE_ASIF","as");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasMaxLength(4);

                    b.Property<int>("IdOperationTypeFamily")
                        .HasColumnName("ID_OPERATION_TYPE_FAMILY");

                    b.Property<int>("IdUserGroup")
                        .HasColumnName("ID_USER_GROUP");

                    b.Property<bool>("IsMandatory")
                        .HasColumnName("IS_MANDATORY");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdOperationTypeFamily");

                    b.ToTable("OPERATION_TYPE","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTypeFamily", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasMaxLength(4);

                    b.Property<int>("IdAsset")
                        .HasColumnName("ID_ASSET");

                    b.Property<int>("IdMovement")
                        .HasColumnName("ID_MOVEMENT");

                    b.Property<int>("IdUserGroup")
                        .HasColumnName("ID_USER_GROUP");

                    b.Property<bool>("IsMandatory")
                        .HasColumnName("IS_MANDATORY");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdAsset");

                    b.HasIndex("IdMovement");

                    b.HasIndex("Id", "IdMovement")
                        .IsUnique()
                        .HasName("IX_OTF_Id_IdMovement");

                    b.ToTable("OPERATION_TYPE_FAMILY","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.Property<string>("ImportFileDir")
                        .HasColumnName("IMPORT_FILE_DIR")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("PARAMETER","gen");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Plan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Color")
                        .HasColumnName("COLOR");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(100);

                    b.Property<int>("Year")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.ToTable("PLAN","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdAccount")
                        .HasColumnName("ID_ACCOUNT");

                    b.Property<int>("IdPlan")
                        .HasColumnName("ID_PLAN");

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdPlan");

                    b.ToTable("PLAN_ACCOUNT","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPoste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPlan")
                        .HasColumnName("ID_PLAN");

                    b.Property<int>("IdPoste")
                        .HasColumnName("ID_POSTE");

                    b.Property<int>("IdReferenceTable")
                        .HasColumnName("ID_REFERENCE_TABLE");

                    b.Property<string>("Label")
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdPoste");

                    b.HasIndex("IdReferenceTable");

                    b.ToTable("PLAN_POSTE","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPosteFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdFrequency")
                        .HasColumnName("ID_FREQUENCY");

                    b.Property<int>("IdPlanPoste")
                        .HasColumnName("ID_PLAN_POSTE");

                    b.Property<double>("PreviewAmount")
                        .HasColumnName("PREVIEW_AMOUNT");

                    b.HasKey("Id");

                    b.HasIndex("IdFrequency");

                    b.HasIndex("IdPlanPoste");

                    b.ToTable("PLAN_POSTE_FREQUENCY","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPosteReference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPlanPoste")
                        .HasColumnName("ID_PLAN_POSTE");

                    b.Property<int>("IdReference")
                        .HasColumnName("ID_REFERENCE");

                    b.Property<int>("IdReferenceTable")
                        .HasColumnName("ID_REFERENCE_TABLE");

                    b.HasKey("Id");

                    b.HasIndex("IdPlanPoste");

                    b.HasIndex("IdReferenceTable");

                    b.ToTable("PLAN_POSTE_REFERENCE","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPosteUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPlanPoste")
                        .HasColumnName("ID_PLAN_POSTE");

                    b.Property<int>("IdPlanUser")
                        .HasColumnName("ID_PLAN_USER");

                    b.Property<int>("IsSalaryEstimatedPart")
                        .HasColumnName("IS_SALARY_ESTIMATED_PART");

                    b.Property<double>("PercentagePart")
                        .HasColumnName("PERCENTAGE_PART");

                    b.HasKey("Id");

                    b.HasIndex("IdPlanPoste");

                    b.HasIndex("IdPlanUser");

                    b.ToTable("PLAN_POSTE_USER","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdPlan")
                        .HasColumnName("ID_PLAN");

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdPlan", "IdUser")
                        .IsUnique()
                        .HasName("IX_PlanUser");

                    b.ToTable("PLAN_USER","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Poste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("POSTE","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.ReferenceTable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnName("LABEL");

                    b.Property<string>("TableName")
                        .HasColumnName("TABLE_NAME");

                    b.HasKey("Id");

                    b.ToTable("REFERENCE_TABLE","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Database.StateAsif", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnName("LABEL");

                    b.HasKey("Id");

                    b.ToTable("STATE_ASIF","ref");
                });

            modelBuilder.Entity("Budget.MODEL.Database.UserAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivationCode")
                        .HasColumnName("ACTIVATION_CODE");

                    b.Property<int>("IdAccount")
                        .HasColumnName("ID_ACCOUNT");

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdUser");

                    b.ToTable("USER_ACCOUNT","user");
                });

            modelBuilder.Entity("Budget.MODEL.Database.UserCustomOtf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("IdAccount")
                        .HasColumnName("ID_ACCOUNT");

                    b.Property<int>("IdOperationTypeFamily")
                        .HasColumnName("ID_OPERATION_TYPE_FAMILY");

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.HasKey("Id");

                    b.HasIndex("IdAccount");

                    b.HasIndex("IdUser");

                    b.HasIndex("IdOperationTypeFamily", "IdUser", "IdAccount")
                        .IsUnique()
                        .HasName("IX_UCO_IdOperationTypeFamily_IdUser_IdAccount")
                        .HasFilter("[ID_ACCOUNT] IS NOT NULL");

                    b.ToTable("USER_CUSTOM_OTF","user");
                });

            modelBuilder.Entity("Budget.MODEL.Database.VPlanGlobal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double?>("AmountOperation")
                        .HasColumnName("AMOUNT_OPERATION");

                    b.Property<DateTime?>("DateIntegration")
                        .HasColumnName("DATE_INTEGRATION");

                    b.Property<int?>("IdAccountStatement")
                        .HasColumnName("ID_ACCOUNT_STATEMENT");

                    b.Property<int?>("IdPlan")
                        .HasColumnName("ID_PLAN");

                    b.Property<int?>("IdPlanPoste")
                        .HasColumnName("ID_PLAN_POSTE");

                    b.Property<int?>("IdPoste")
                        .HasColumnName("ID_POSTE");

                    b.Property<int?>("IdReference")
                        .HasColumnName("ID_REFERENCE");

                    b.Property<string>("LabelReference")
                        .HasColumnName("LABEL_REFERENCE");

                    b.Property<int?>("Month")
                        .HasColumnName("MONTH");

                    b.Property<string>("PlanPosteLabel")
                        .HasColumnName("PLAN_POSTE_LABEL");

                    b.Property<double?>("PreviewAmount")
                        .HasColumnName("PREVIEW_AMOUNT");

                    b.Property<int?>("Year")
                        .HasColumnName("YEAR");

                    b.HasKey("Id");

                    b.ToTable("V_PLAN_GLOBAL","plan");
                });

            modelBuilder.Entity("Budget.MODEL.Dto.BaseChartData", b =>
                {
                    b.Property<int>("Id");

                    b.Property<double>("Amount");

                    b.Property<string>("Month");

                    b.Property<int>("Year");

                    b.HasKey("Id", "Amount");

                    b.ToTable("BaseChartData");
                });

            modelBuilder.Entity("Budget.MODEL.Dto.SelectNameValueDto<double>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.Property<double>("Value");

                    b.HasKey("Id");

                    b.ToTable("SelectNameValueDto");
                });

            modelBuilder.Entity("Budget.MODEL.Dto.SoldeDto", b =>
                {
                    b.Property<double>("Credit");

                    b.Property<double>("Debit");

                    b.Property<int>("IdAccount");

                    b.Property<double>("Solde");

                    b.Property<double>("Total");

                    b.HasKey("Credit");

                    b.ToTable("SoldeDto");
                });

            modelBuilder.Entity("Budget.MODEL.Movement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Label")
                        .HasColumnName("LABEL")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("MOVEMENT","ref");
                });

            modelBuilder.Entity("Budget.MODEL.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ActivationCode")
                        .HasColumnName("ACTIVATION_CODE");

                    b.Property<string>("AvatarUrl")
                        .HasColumnName("AVATAR_URL");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnName("CREATION_DATE");

                    b.Property<DateTime>("DateLastActive")
                        .HasColumnName("LAST_ACTIVE_DATE");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnName("BIRTH_DATE");

                    b.Property<string>("FirstName")
                        .HasColumnName("FIRST_NAME");

                    b.Property<string>("Gender")
                        .HasColumnName("GENDER");

                    b.Property<string>("IdAvatarCloud")
                        .HasColumnName("ID_AVATAR_CLOUD");

                    b.Property<int?>("IdGMapAddress")
                        .HasColumnName("ID_GMAP_ADDRESS");

                    b.Property<int>("IdUserGroup")
                        .HasColumnName("ID_USER_GROUP");

                    b.Property<bool>("IsMailConfirmed")
                        .HasColumnName("IS_MAIL_CONFIRMED");

                    b.Property<string>("LastName")
                        .HasColumnName("LAST_NAME");

                    b.Property<string>("MailAddress")
                        .HasColumnName("MAIL_ADDRESS");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnName("PASSWORD_HASH");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnName("PASSWORD_SALT");

                    b.Property<string>("Role")
                        .HasColumnName("ROLE");

                    b.Property<string>("UserName")
                        .HasColumnName("USER_NAME");

                    b.HasKey("Id");

                    b.HasIndex("IdGMapAddress");

                    b.ToTable("USER","user");
                });

            modelBuilder.Entity("Budget.MODEL.UserShortcut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("ID")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Icon")
                        .HasColumnName("ICON");

                    b.Property<int>("IdUser")
                        .HasColumnName("ID_USER");

                    b.Property<string>("Title")
                        .HasColumnName("TITLE");

                    b.Property<string>("Type")
                        .HasColumnName("TYPE");

                    b.Property<string>("Url")
                        .HasColumnName("URL");

                    b.HasKey("Id");

                    b.HasIndex("IdUser");

                    b.ToTable("USER_SHORTCUT","user");
                });

            modelBuilder.Entity("Budget.MODEL.Database.Account", b =>
                {
                    b.HasOne("Budget.MODEL.Database.AccountType", "AccountType")
                        .WithMany()
                        .HasForeignKey("IdAccountType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.BankAgency", "BankAgency")
                        .WithMany("Accounts")
                        .HasForeignKey("IdBankAgency")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.User", "UserOwner")
                        .WithMany()
                        .HasForeignKey("IdUserOwner")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatement", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.AccountStatementImport", "AccountStatementImport")
                        .WithMany()
                        .HasForeignKey("IdImport")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationDetail", "OperationDetail")
                        .WithMany()
                        .HasForeignKey("IdOperationDetail")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationMethod", "OperationMethod")
                        .WithMany()
                        .HasForeignKey("IdOperationMethod")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("IdOperationType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationTypeFamily", "OperationTypeFamily")
                        .WithMany()
                        .HasForeignKey("IdOperationTypeFamily")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatementImport", b =>
                {
                    b.HasOne("Budget.MODEL.Database.BankAgency", "BankAgency")
                        .WithMany()
                        .HasForeignKey("IdBankAgency")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatementImportFile", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IdAccount");

                    b.HasOne("Budget.MODEL.Database.AccountStatementImport", "AccountStatementImport")
                        .WithMany()
                        .HasForeignKey("IdImport")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationDetail", "OperationDetail")
                        .WithMany()
                        .HasForeignKey("IdOperationDetail")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationMethod", "OperationMethod")
                        .WithMany()
                        .HasForeignKey("IdOperationMethod")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("IdOperationType")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationTypeFamily", "OperationTypeFamily")
                        .WithMany()
                        .HasForeignKey("IdOperationTypeFamily")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.StateAsif", "State")
                        .WithMany()
                        .HasForeignKey("IdState")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.AccountStatementPlan", b =>
                {
                    b.HasOne("Budget.MODEL.Database.AccountStatement", "AccountStatement")
                        .WithMany()
                        .HasForeignKey("IdAccountStatement")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankAgency", b =>
                {
                    b.HasOne("Budget.MODEL.Database.BankSubFamily", "BankSubFamily")
                        .WithMany()
                        .HasForeignKey("IdBankSubFamily")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapAddress", "GMapAddress")
                        .WithMany()
                        .HasForeignKey("IdGMapAddress")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankFamily", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("IdAsset")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankFileDefinition", b =>
                {
                    b.HasOne("Budget.MODEL.Database.BankFamily", "BankFamily")
                        .WithMany()
                        .HasForeignKey("IdBankFamily")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.BankSubFamily", b =>
                {
                    b.HasOne("Budget.MODEL.Database.BankFamily", "BankFamily")
                        .WithMany()
                        .HasForeignKey("IdBankFamily")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapAddress", b =>
                {
                    b.HasOne("Budget.MODEL.Database.GMapAdministrativeAreaLevel1", "gMapAdministrativeAreaLevel1")
                        .WithMany()
                        .HasForeignKey("idGMapAdministrativeAreaLevel1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapAdministrativeAreaLevel2", "gMapAdministrativeAreaLevel2")
                        .WithMany()
                        .HasForeignKey("idGMapAdministrativeAreaLevel2")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapCountry", "gMapCountry")
                        .WithMany()
                        .HasForeignKey("idGMapCountry")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapLocality", "gMapLocality")
                        .WithMany()
                        .HasForeignKey("idGMapLocality")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapNeighborhood", "gMapNeighborhood")
                        .WithMany()
                        .HasForeignKey("idGMapNeighborhood")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapPostalCode", "gMapPostalCode")
                        .WithMany()
                        .HasForeignKey("idGMapPostalCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapRoute", "gMapRoute")
                        .WithMany()
                        .HasForeignKey("idGMapRoute")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapStreetNumber", "gMapStreetNumber")
                        .WithMany()
                        .HasForeignKey("idGMapStreetNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapSublocalityLevel1", "gMapSublocalityLevel1")
                        .WithMany()
                        .HasForeignKey("idGMapSublocalityLevel1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapSublocalityLevel2", "gMapSublocalityLevel2")
                        .WithMany()
                        .HasForeignKey("idGMapSublocalityLevel2")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapAddressType", b =>
                {
                    b.HasOne("Budget.MODEL.Database.GMapAddress", "GMapAddress")
                        .WithMany()
                        .HasForeignKey("IdGMapAddress")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.GMapType", "GMapType")
                        .WithMany()
                        .HasForeignKey("IdGMapType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.GMapTypeLanguage", b =>
                {
                    b.HasOne("Budget.MODEL.Database.GMapType", "GMapType")
                        .WithMany()
                        .HasForeignKey("IdGMapType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.Operation", b =>
                {
                    b.HasOne("Budget.MODEL.Database.OperationMethod", "OperationMethod")
                        .WithMany()
                        .HasForeignKey("IdOperationMethod")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationType", "OperationType")
                        .WithMany()
                        .HasForeignKey("IdOperationType")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationDetail", b =>
                {
                    b.HasOne("Budget.MODEL.Database.GMapAddress", "GMapAddress")
                        .WithMany()
                        .HasForeignKey("IdGMapAddress")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.Operation", "Operation")
                        .WithMany()
                        .HasForeignKey("IdOperation")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationMethodLexical", b =>
                {
                    b.HasOne("Budget.MODEL.Database.OperationMethod", "OperationMethod")
                        .WithMany()
                        .HasForeignKey("IdOperationMethod")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTransverse", b =>
                {
                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTransverseAs", b =>
                {
                    b.HasOne("Budget.MODEL.Database.AccountStatement", "AccountStatement")
                        .WithMany()
                        .HasForeignKey("IdAccountStatement")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationTransverse", "OperationTransverse")
                        .WithMany()
                        .HasForeignKey("IdOperationTransverse")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTransverseAsif", b =>
                {
                    b.HasOne("Budget.MODEL.Database.AccountStatementImportFile", "AccountStatementImportFile")
                        .WithMany()
                        .HasForeignKey("IdAccountStatementImportFile")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.OperationTransverse", "OperationTransverse")
                        .WithMany()
                        .HasForeignKey("IdOperationTransverse")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationType", b =>
                {
                    b.HasOne("Budget.MODEL.Database.OperationTypeFamily", "OperationTypeFamily")
                        .WithMany()
                        .HasForeignKey("IdOperationTypeFamily")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.OperationTypeFamily", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Asset", "Asset")
                        .WithMany()
                        .HasForeignKey("IdAsset")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Movement", "Movement")
                        .WithMany()
                        .HasForeignKey("IdMovement")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.Parameter", b =>
                {
                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanAccount", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPoste", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.Poste", "Poste")
                        .WithMany()
                        .HasForeignKey("IdPoste")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.ReferenceTable", "ReferenceTable")
                        .WithMany()
                        .HasForeignKey("IdReferenceTable")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPosteFrequency", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Month", "Frequency")
                        .WithMany()
                        .HasForeignKey("IdFrequency")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.PlanPoste", "PlanPoste")
                        .WithMany()
                        .HasForeignKey("IdPlanPoste")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPosteReference", b =>
                {
                    b.HasOne("Budget.MODEL.Database.PlanPoste", "PlanPoste")
                        .WithMany()
                        .HasForeignKey("IdPlanPoste")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.ReferenceTable", "ReferenceTable")
                        .WithMany()
                        .HasForeignKey("IdReferenceTable")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanPosteUser", b =>
                {
                    b.HasOne("Budget.MODEL.Database.PlanPoste", "PlanPoste")
                        .WithMany()
                        .HasForeignKey("IdPlanPoste")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.Database.PlanUser", "PlanUser")
                        .WithMany()
                        .HasForeignKey("IdPlanUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.PlanUser", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Plan", "Plan")
                        .WithMany()
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.UserAccount", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Account", "Account")
                        .WithMany("UserAccounts")
                        .HasForeignKey("IdAccount")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany("UserAccounts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.Database.UserCustomOtf", b =>
                {
                    b.HasOne("Budget.MODEL.Database.Account", "Account")
                        .WithMany()
                        .HasForeignKey("IdAccount");

                    b.HasOne("Budget.MODEL.Database.OperationTypeFamily", "OperationTypeFamily")
                        .WithMany()
                        .HasForeignKey("IdOperationTypeFamily")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany()
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Budget.MODEL.User", b =>
                {
                    b.HasOne("Budget.MODEL.Database.GMapAddress", "GMapAddress")
                        .WithMany()
                        .HasForeignKey("IdGMapAddress");
                });

            modelBuilder.Entity("Budget.MODEL.UserShortcut", b =>
                {
                    b.HasOne("Budget.MODEL.User", "User")
                        .WithMany("Shortcuts")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
